# ------------------------
# Sample environment file for supported customizations
# - automatically read by `scripts/configure.sh`
# - comments will be ignored
# 
# A few notes on NAMING:
# - hierarchy will be flattened (each level separated by underscore)
# - resulting environment variables are in uppercase
# ------------------------
## Development
# debug: 
#  enabled: 1
#  ssh_root: 1

## Target platform settings
target:
  machine: "raspberrypi3"

## General settings
env:
  hostname: "yasbi"
  console:
    lang: "en"
  sudo:
    enabled: 1
    nopasswd: 0

## System users & groups
groups:
  add:
    names: "grpone"
users:
  root:
    pwd: "yasbi"
  add:
    # Specify one or more additional users here (separate by semicolon)
    users:  "userone;usertwo;userthree"
    pwds:   "useronepw;usertwopw;userthreepw"
    groups: "sudo;grpone;"

## Features
#net:
# Only supports ipv4 currently
#  static_ip: ""
#  dns_server: ""
wifi:
  enabled: 1
  mode: "client"
  ssid: "yasbinet"
  pwd: "fortytwo"
bt:
  enabled: 1
ssh:
  enabled: 1

## Application
app:
  cmake:
    url: "github.com/JSydll/iot-sample-app.git"
    # tag: ""
    autoload: 1
    install_path: "/usr/bin"
    executable: "iot-sample-app"
    exec_user: "userone"