# ------------------------
# Sample environment file for supported customizations
# - automatically read by `scripts/configure.sh`
# - comments will be ignored
# 
# A few notes on NAMING:
# - hierarchy will be flattened (each level separated by underscore)
# - resulting environment variables are in uppercase
# ------------------------
## Target platform settings
target:
  machine: "raspberrypi3"

## General settings
settings:
  hostname: "yasbi"
  console:
    lang: "en"

## System users
users:
  root:
    pwd: "yasbi"
  add:
    # Specify one or more additional users here (separate by semicolon)
    users: "userone;usertwo"
    pwds:  "useronepw;usertwopw"

## Features
#net:
# Only supports ipv4 currently
#  static_ip: ""
#  dns_server: ""
wifi:
  enabled: 1
  mode: "client"
  ssid: "yasbinet"
  pwd: "fortytwo"
bt:
  enabled: 1